//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int Id { get; set; }
        public string AD_Name { get; set; }
        public string AD_email { get; set; }
        public string AD_Password { get; set; }
    }
}
