//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int IID { get; set; }
        public int code { get; set; }
        public string category { get; set; }
        public string IName { get; set; }
        public Nullable<int> IPrice { get; set; }
    }
}
